{% set name = "eva-sub-cli" %}
{% set version = "0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../
#  url: https://github.com/EBIvariation/eva-sub-cli/archive/v{{version}}.tar.gz
#  sha256:

build:
  number: 0
  noarch: generic
  preserve_egg_dir: True
#  run_exports:
#    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  host:
    - nextflow >=21.10.0
    - python >=3.8
    - pip
    # biovalidator
    - nodejs >=10.19.1
  run:
    - nextflow >=21.10.0
    - python >=3.8

test:
  imports:
    - eva_sub_cli
  commands:
    - biovalidator --help
    - vcf_validator --help
    - eva-sub-cli.py --help

about:
  home: https://github.com/EBIvariation/eva-sub-cli
  summary: EVA Submission Command Line Interface
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apriltuesday